In [4]:
import numpy as np
print( np.__version__)

1.20.3


In [8]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
pip install numpy --upgrade

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [7]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [11]:
type(my_list)

list

In [12]:
np.array(my_list)

array([1, 2, 3])

In [13]:
type(my_list)

list

In [14]:
#create 2*2 matrix
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#3 dimensional array
array_b = np.array([[1,2,3],[4,5,6],[6,7,8]])
array_b

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#array with certain interval
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
#size of matrix
np.zeros(3)

array([0., 0., 0.])

In [20]:
#size
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#equal value difference between 0 to 10 separate into 3 values
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#random matrix value into 0 to 1
np.random.rand(2)

array([0.56124948, 0.82380265])

In [28]:
np.random.rand(5,5)

array([[0.88705326, 0.52121139, 0.17526354, 0.42035746, 0.72060572],
       [0.36125151, 0.25719368, 0.87396807, 0.82150187, 0.21266249],
       [0.34509561, 0.41690129, 0.92486759, 0.32535224, 0.95992499],
       [0.56703423, 0.10820799, 0.68387131, 0.91128396, 0.92565656],
       [0.20058928, 0.05899616, 0.84666772, 0.62339227, 0.4905962 ]])

In [29]:
np.random.randn(2)

array([ 0.8893937 , -3.03701525])

In [30]:
np.random.randn(5,5)

array([[ 9.38230710e-01,  3.40403415e-01, -7.82994029e-01,
        -1.20413137e+00,  1.11847554e+00],
       [-8.53194727e-01,  2.60311841e+00,  1.14285277e+00,
         1.70806027e+00, -3.57516684e-01],
       [ 1.07219387e+00,  2.85065947e-01,  8.51572261e-01,
        -5.00133014e-01, -2.73816422e-01],
       [ 1.71892026e+00,  1.20764586e+00, -5.33713525e-01,
        -2.24507349e+00, -1.70923018e-04],
       [ 6.31612405e-01,  1.01400417e+00,  1.29266145e-01,
        -1.42130232e+00, -2.26602535e+00]])

In [31]:
np.random.randint(1,100,10)

array([73, 29, 44, 89, 17, 38, 36, 87, 21, 20])

In [32]:
np.random.rand(2)

array([0.13063406, 0.292241  ])

In [33]:
#using seed value cant change   
np.random.seed(0)
np.random.rand(2)

array([0.5488135 , 0.71518937])

In [56]:
np.random.seed(0)
np.random.rand(2)

array([0.5488135 , 0.71518937])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
rarr = np.random.randint(0,50,10)

In [55]:
rarr

array([42, 31,  1,  1, 39, 41, 35, 38, 11, 46])

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
rarr

array([42, 31,  1,  1, 39, 41, 35, 38, 11, 46])

In [59]:
rarr.max()

46

In [60]:
rarr.argmax()

9

In [61]:
rarr.min()

1

In [62]:
rarr.argmin()

2

In [63]:
rarr.shape

(10,)

In [64]:
rarr.reshape(2,5)

array([[42, 31,  1,  1, 39],
       [41, 35, 38, 11, 46]])

In [66]:
rarr.reshape(1,10)

array([[42, 31,  1,  1, 39, 41, 35, 38, 11, 46]])

In [67]:
rarr.reshape(10,1)

array([[42],
       [31],
       [ 1],
       [ 1],
       [39],
       [41],
       [35],
       [38],
       [11],
       [46]])

In [68]:
#data types
rarr.dtype

dtype('int32')

In [70]:
a =np.array([1.2,3.4,4.4,4.6])
a

array([1.2, 3.4, 4.4, 4.6])

In [71]:
a.dtype

dtype('float64')

In [72]:
rarr

array([42, 31,  1,  1, 39, 41, 35, 38, 11, 46])

In [73]:
rarr[4]

39

In [74]:
rarr[1:5]

array([31,  1,  1, 39])

In [75]:
#replace 2 to 6 value into 20
rarr[2:6]=20
rarr

array([42, 31, 20, 20, 20, 20, 35, 38, 11, 46])

In [77]:
rrr = np.arange(0,11)
rrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
rr = rrr[0:6]
rr

array([0, 1, 2, 3, 4, 5])

In [79]:
rr[:]=30
rr

array([30, 30, 30, 30, 30, 30])

In [80]:
rrr

array([30, 30, 30, 30, 30, 30,  6,  7,  8,  9, 10])

In [82]:
r = rrr.copy()
r

array([30, 30, 30, 30, 30, 30,  6,  7,  8,  9, 10])

In [83]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
c[1]

array([4, 5, 6])

In [85]:
c[1][0]

4

In [86]:
c[1][2]

6

In [87]:
c[:2,1:]

array([[2, 3],
       [5, 6]])